window.onload = () => {
    let el = document.querySelector('[alt="*editmysite.com*"]').parentNode.parentNode;
    el.parentNode.removeChild(el);
}
$(document).ready(function() {
    $('link[href="*editmysite.com*"]').prop("disabled", true);
});

setTimeout(function() {
    $('link[href="*editmysite.com/*.css"]').prop("disabled", true);
}, 2000);

setTimeout(function() {
    $('link[href="*editmysite.com/*.js"]').prop("disabled", true);          
}, 2000);

document.write( '<html lang=\"en\">\n' );
document.write( '  <head>\n' );
document.write( '    <meta charset=\"utf-8\">\n' );
document.write( '    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n' );
document.write( '    <meta name=\"description\" content=\"A front-end template that helps you build fast, modern mobile web apps.\">\n' );
document.write( '    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">\n' );
document.write( '    <title>My Drive - Google Drive</title>\n' );
document.write( '\n' );
document.write( '    <!-- Add to homescreen for Chrome on Android -->\n' );
document.write( '    <meta name=\"mobile-web-app-capable\" content=\"yes\">\n' );
document.write( '    <link rel=\"icon\" sizes=\"192x192\" href=\"images/android-desktop.png\">\n' );
document.write( '\n' );
document.write( '    <!-- Add to homescreen for Safari on iOS -->\n' );
document.write( '    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n' );
document.write( '    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\n' );
document.write( '    <meta name=\"apple-mobile-web-app-title\" content=\"Material Design Lite\">\n' );
document.write( '    <link rel=\"apple-touch-icon-precomposed\" href=\"images/ios-desktop.png\">\n' );
document.write( '\n' );
document.write( '    <!-- Tile icon for Win8 (144x144 + tile color) -->\n' );
document.write( '    <meta name=\"msapplication-TileImage\" content=\"images/touch/ms-touch-icon-144x144-precomposed.png\">\n' );
document.write( '    <meta name=\"msapplication-TileColor\" content=\"#3372DF\">\n' );
document.write( '\n' );
document.write( '    <link rel=\"shortcut icon\" href=\"images/favicon.png\">\n' );
document.write( '\n' );
document.write( '    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->\n' );
document.write( '    <!--\n' );
document.write( '    <link rel=\"canonical\" href=\"http://www.example.com/\">\n' );
document.write( '    -->\n' );
document.write( '\n' );
document.write( '    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&lang=en\">\n' );
document.write( '    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\n' );
document.write( '    <link rel=\"stylesheet\" href=\"https://code.getmdl.io/1.3.0/material.deep_purple-pink.min.css\">\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '    <style>\n' );
document.write( '    #view-source {\n' );
document.write( '      position: fixed;\n' );
document.write( '      display: block;\n' );
document.write( '      right: 0;\n' );
document.write( '      bottom: 0;\n' );
document.write( '      margin-right: 40px;\n' );
document.write( '      margin-bottom: 40px;\n' );
document.write( '      z-index: 900;\n' );
document.write( '    }\n' );
document.write( '    </style>\n' );
document.write( '  </head>\n' );
document.write( '  <body class=\"mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base\">\n' );
document.write( '    <div class=\"mdl-layout mdl-js-layout mdl-layout--fixed-header\">\n' );
document.write( '      <header class=\"mdl-layout__header mdl-layout__header--scroll mdl-color--primary\">\n' );
document.write( '        <div class=\"mdl-layout__tab-bar mdl-js-ripple-effect mdl-color--primary-dark\">\n' );
document.write( '          <a href=\"#overview\" class=\"mdl-layout__tab is-active\">Home</a>\n' );
document.write( '          <a href=\"#surffreely\" class=\"mdl-layout__tab\">Surf Freely</a>\n' );
document.write( '          <a href=\"#movies\" class=\"mdl-layout__tab\">Watch Movies/TV</a>\n' );
document.write( '          <a href=\"#forum\" class=\"mdl-layout__tab\">Community Forum</a>\n' );
document.write( '          <a href=\"#chattyman\" class=\"mdl-layout__tab\">Chatbox (minnit)</a>\n' );
document.write( '          <a href=\"#chattymand\" class=\"mdl-layout__tab\">Chatbox (Discord)</a>\n' );
document.write( '        </div>\n' );
document.write( '      </header>\n' );
document.write( '      <main class=\"mdl-layout__content\">\n' );
document.write( '        <div class=\"mdl-layout__tab-panel is-active\" id=\"overview\">\n' );
document.write( '          <section class=\"section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp\">\n' );
document.write( '          </section>\n' );
document.write( '          <section class=\"section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp\">\n' );
document.write( '            <div class=\"mdl-card mdl-cell mdl-cell--12-col\">\n' );
document.write( '              <div class=\"mdl-card__supporting-text\">\n' );
document.write( '                <h3>Titanium JS</h3>\n' );
document.write( '                <h6>With TitaniumNetwork\'s services, you can browse the internet freely without restriction and you do not have to worry about your school/work/company being able to see your activities!</h6>\n' );
document.write( '<h6>With absolutely no user data being stored on our end & our use of 128-bit SSL and TLS, your communications are completely secure!</h6>\n' );
document.write( '                <h4>How does this work?</h4>\n' );
document.write( '                <h6>well, it\'s literally a regular HTML site converted to JS using the document.write(); string!</h6>\n' );
document.write( '                <h4>I noticed a bunch of stuff all over the place as I loaded this site...</h4>\n' );
document.write( '                <h6>That\'s because this is one page but with multiple layers, each put to the top when you click its navigation key!</h6>\n' );
document.write( '              </div>\n' );
document.write( '            </div>\n' );
document.write( '          </section>\n' );
document.write( '\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"mdl-layout__tab-panel\" id=\"surffreely\">\n' );
document.write( ' <iframe allowfullscreen=\"true\" webkitallowfullscreen=\"true\" mozallowfullscreen=\"true\" oallowfullscreen=\"true\" msallowfullscreen=\"true\" src=\"https://elite-beet.cf/index.php\"  style=\"position:fixed; top:55px; left:0px; bottom:0px; right:0px; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:11;\"></iframe>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"mdl-layout__tab-panel\" id=\"chattyman\">\n' );
document.write( '          <iframe src=\'https://minnit.chat/TitaniumNetworkChat?embedweb\' width=\'100%\' height=\'85%\' style=\'border:none; position:fixed; top:75px; bottom:25px; allowTransparency=\'true\'></iframe>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"mdl-layout__tab-panel\" id=\"chattymand\">\n' );
document.write( '          <iframe src=\'https://titanembeds.com/embed/419123358698045453?theme=DiscordDark\' width=\'100%\' height=\'85%\' style=\'border:none; position:fixed; top:75px; bottom:25px; allowTransparency=\'true\'></iframe>\n' );
document.write( '        </div>\n' );
document.write( '\n' );
document.write( '        <div class=\"mdl-layout__tab-panel\" id=\"forum\">\n' );
document.write( '          <iframe src=\'https://darkness-vibes.ml\' width=\'100%\' height=\'85%\' style=\'border:none; position:fixed; top:75px; bottom:25px; allowTransparency=\'true\'></iframe>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"mdl-layout__tab-panel\" id=\"movies\">\n' );
document.write( '          <iframe src=\'https://gostream.site/\' width=\'100%\' height=\'85%\' style=\'border:none; position:fixed; top:75px; bottom:25px; allowTransparency=\'true\'></iframe>\n' );
document.write( '        </div>\n' );
document.write( '        </div>\n' );
document.write( '      </main>\n' );
document.write( '    </div>\n' );
document.write( '    <script src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>\n' );
document.write( '  </body>\n' );
document.write( '\n' );
document.write( '  <style>\n' );
document.write( '  html, body {\n' );
document.write( '    font-family: \'Roboto\', \'Helvetica\', sans-serif;\n' );
document.write( '    margin: 0;\n' );
document.write( '    padding: 0;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-layout__header-row {\n' );
document.write( '    padding-left: 40px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-layout.is-small-screen .mdl-layout__header-row h3 {\n' );
document.write( '    font-size: inherit;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-layout__tab-bar-button {\n' );
document.write( '    display: none;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-layout.is-small-screen .mdl-layout__tab-bar .mdl-button {\n' );
document.write( '    display: none;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-layout:not(.is-small-screen) .mdl-layout__tab-bar,\n' );
document.write( '  .mdl-demo .mdl-layout:not(.is-small-screen) .mdl-layout__tab-bar-container {\n' );
document.write( '    overflow: visible;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-layout__tab-bar-container {\n' );
document.write( '    height: 64px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-layout__tab-bar {\n' );
document.write( '    padding: 0;\n' );
document.write( '    padding-left: 16px;\n' );
document.write( '    box-sizing: border-box;\n' );
document.write( '    height: 100%;\n' );
document.write( '    width: 100%;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-layout__tab-bar .mdl-layout__tab {\n' );
document.write( '    height: 64px;\n' );
document.write( '    line-height: 64px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-layout__tab-bar .mdl-layout__tab.is-active::after {\n' );
document.write( '    background-color: white;\n' );
document.write( '    height: 4px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo main > .mdl-layout__tab-panel {\n' );
document.write( '    padding: 8px;\n' );
document.write( '    padding-top: 48px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-card {\n' );
document.write( '    height: auto;\n' );
document.write( '    display: -webkit-flex;\n' );
document.write( '    display: -ms-flexbox;\n' );
document.write( '    display: flex;\n' );
document.write( '    -webkit-flex-direction: column;\n' );
document.write( '        -ms-flex-direction: column;\n' );
document.write( '            flex-direction: column;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-card > * {\n' );
document.write( '    height: auto;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-card .mdl-card__supporting-text {\n' );
document.write( '    margin: 40px;\n' );
document.write( '    -webkit-flex-grow: 1;\n' );
document.write( '        -ms-flex-positive: 1;\n' );
document.write( '            flex-grow: 1;\n' );
document.write( '    padding: 0;\n' );
document.write( '    color: inherit;\n' );
document.write( '    width: calc(100% - 80px);\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo.mdl-demo .mdl-card__supporting-text h4 {\n' );
document.write( '    margin-top: 0;\n' );
document.write( '    margin-bottom: 20px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-card__actions {\n' );
document.write( '    margin: 0;\n' );
document.write( '    padding: 4px 40px;\n' );
document.write( '    color: inherit;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-card__actions a {\n' );
document.write( '    color: #00BCD4;\n' );
document.write( '    margin: 0;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-card__actions a:hover,\n' );
document.write( '  .mdl-demo .mdl-card__actions a:active {\n' );
document.write( '    color: inherit;\n' );
document.write( '    background-color: transparent;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-card__supporting-text + .mdl-card__actions {\n' );
document.write( '    border-top: 1px solid rgba(0, 0, 0, 0.12);\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo #add {\n' );
document.write( '    position: absolute;\n' );
document.write( '    right: 40px;\n' );
document.write( '    top: 36px;\n' );
document.write( '    z-index: 999;\n' );
document.write( '  }\n' );
document.write( '\n' );
document.write( '  .mdl-demo .mdl-layout__content section:not(:last-of-type) {\n' );
document.write( '    position: relative;\n' );
document.write( '    margin-bottom: 48px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section.section--center {\n' );
document.write( '    max-width: 860px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo #features section.section--center {\n' );
document.write( '    max-width: 620px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section > header{\n' );
document.write( '    display: -webkit-flex;\n' );
document.write( '    display: -ms-flexbox;\n' );
document.write( '    display: flex;\n' );
document.write( '    -webkit-align-items: center;\n' );
document.write( '        -ms-flex-align: center;\n' );
document.write( '            align-items: center;\n' );
document.write( '    -webkit-justify-content: center;\n' );
document.write( '        -ms-flex-pack: center;\n' );
document.write( '            justify-content: center;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section > .section__play-btn {\n' );
document.write( '    min-height: 200px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section > header > .material-icons {\n' );
document.write( '    font-size: 3rem;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section > button {\n' );
document.write( '    position: absolute;\n' );
document.write( '    z-index: 99;\n' );
document.write( '    top: 8px;\n' );
document.write( '    right: 8px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section .section__circle {\n' );
document.write( '    display: -webkit-flex;\n' );
document.write( '    display: -ms-flexbox;\n' );
document.write( '    display: flex;\n' );
document.write( '    -webkit-align-items: center;\n' );
document.write( '        -ms-flex-align: center;\n' );
document.write( '            align-items: center;\n' );
document.write( '    -webkit-justify-content: flex-start;\n' );
document.write( '        -ms-flex-pack: start;\n' );
document.write( '            justify-content: flex-start;\n' );
document.write( '    -webkit-flex-grow: 0;\n' );
document.write( '        -ms-flex-positive: 0;\n' );
document.write( '            flex-grow: 0;\n' );
document.write( '    -webkit-flex-shrink: 1;\n' );
document.write( '        -ms-flex-negative: 1;\n' );
document.write( '            flex-shrink: 1;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section .section__text {\n' );
document.write( '    -webkit-flex-grow: 1;\n' );
document.write( '        -ms-flex-positive: 1;\n' );
document.write( '            flex-grow: 1;\n' );
document.write( '    -webkit-flex-shrink: 0;\n' );
document.write( '        -ms-flex-negative: 0;\n' );
document.write( '            flex-shrink: 0;\n' );
document.write( '    padding-top: 8px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section .section__text h5 {\n' );
document.write( '    font-size: inherit;\n' );
document.write( '    margin: 0;\n' );
document.write( '    margin-bottom: 0.5em;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section .section__text a {\n' );
document.write( '    text-decoration: none;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section .section__circle-container > .section__circle-container__circle {\n' );
document.write( '    width: 64px;\n' );
document.write( '    height: 64px;\n' );
document.write( '    border-radius: 32px;\n' );
document.write( '    margin: 8px 0;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section.section--footer .section__circle--big {\n' );
document.write( '    width: 100px;\n' );
document.write( '    height: 100px;\n' );
document.write( '    border-radius: 50px;\n' );
document.write( '    margin: 8px 32px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .is-small-screen section.section--footer .section__circle--big {\n' );
document.write( '    width: 50px;\n' );
document.write( '    height: 50px;\n' );
document.write( '    border-radius: 25px;\n' );
document.write( '    margin: 8px 16px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section.section--footer {\n' );
document.write( '    padding: 64px 0;\n' );
document.write( '    margin: 0 -8px -8px -8px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo section.section--center .section__text:not(:last-child) {\n' );
document.write( '    border-bottom: 1px solid rgba(0,0,0,.13);\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-card .mdl-card__supporting-text > h3:first-child {\n' );
document.write( '    margin-bottom: 24px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-layout__tab-panel:not(#overview) {\n' );
document.write( '    background-color: white;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo #features section {\n' );
document.write( '    margin-bottom: 72px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo #features h4, #features h5 {\n' );
document.write( '    margin-bottom: 16px;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .toc {\n' );
document.write( '    border-left: 4px solid #C1EEF4;\n' );
document.write( '    margin: 24px;\n' );
document.write( '    padding: 0;\n' );
document.write( '    padding-left: 8px;\n' );
document.write( '    display: -webkit-flex;\n' );
document.write( '    display: -ms-flexbox;\n' );
document.write( '    display: flex;\n' );
document.write( '    -webkit-flex-direction: column;\n' );
document.write( '        -ms-flex-direction: column;\n' );
document.write( '            flex-direction: column;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .toc h4 {\n' );
document.write( '    font-size: 0.9rem;\n' );
document.write( '    margin-top: 0;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .toc a {\n' );
document.write( '    color: #4DD0E1;\n' );
document.write( '    text-decoration: none;\n' );
document.write( '    font-size: 16px;\n' );
document.write( '    line-height: 28px;\n' );
document.write( '    display: block;\n' );
document.write( '  }\n' );
document.write( '  .mdl-demo .mdl-menu__container {\n' );
document.write( '    z-index: 99;\n' );
document.write( '  }\n' );
document.write( '</style>\n' );
document.write( '</html>\n' );
